services:
  program:
    build:
      dockerfile: ./Dockerfile
      context: ./EfCoreTest/
    environment:
      DB_HOST: my-db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
  db:
    image: postgres:14.2-alpine
    container_name: my-db
    restart: always
    volumes:
      - test-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
volumes:
  test-db-data:
